/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dangeranabinigitedatabase;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ranasgalla.niccolo
 */
public class GiteFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GiteFrame.class.getName());

     private Connection conn;
    /**
     * Creates new form GiteFrame
     */
    public GiteFrame(Connection conn) {
        this.conn = conn;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDestinazione = new javax.swing.JTextField();
        txtDurata = new javax.swing.JTextField();
        txtPrezzo = new javax.swing.JTextField();
        btnCarica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSuccessivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDestinazione.addActionListener(this::txtDestinazioneActionPerformed);

        btnCarica.setText("Carica");
        btnCarica.addActionListener(this::btnCaricaActionPerformed);

        jLabel1.setText("Destinazione");

        jLabel2.setText("Durata");

        jLabel3.setText("Prezzo");

        btnSuccessivo.setText("Prossimo");
        btnSuccessivo.addActionListener(this::btnSuccessivoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDestinazione)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCarica)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDurata)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrezzo)))))
                .addGap(95, 95, 95))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(166, 166, 166)
                    .addComponent(btnSuccessivo)
                    .addContainerGap(405, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDestinazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDurata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnCarica)
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(138, 138, 138)
                    .addComponent(btnSuccessivo)
                    .addContainerGap(239, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDestinazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinazioneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinazioneActionPerformed

    private void btnCaricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaricaActionPerformed
        try {
            String destinazione = txtDestinazione.getText();
            int durata = Integer.parseInt(txtDurata.getText());
            int prezzo = Integer.parseInt(txtPrezzo.getText());

            PreparedStatement pstmt = conn.prepareStatement(
                "INSERT INTO Gite (GIT_Destinazione, GIT_Durata, GIT_Prezzo) VALUES (?, ?, ?)"
            );

            pstmt.setString(1, destinazione);
            pstmt.setInt(2, durata);
            pstmt.setInt(3, prezzo);
            pstmt.execute();
            pstmt.close();

            JOptionPane.showMessageDialog(null, "Destinazione inserita con successo!");

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCaricaActionPerformed

    private void btnSuccessivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuccessivoActionPerformed
      
        AlunniFrame g = new AlunniFrame(conn);
        g.setVisible(true);

    }//GEN-LAST:event_btnSuccessivoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarica;
    private javax.swing.JButton btnSuccessivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDestinazione;
    private javax.swing.JTextField txtDurata;
    private javax.swing.JTextField txtPrezzo;
    // End of variables declaration//GEN-END:variables
}
