/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dangeranabinigitedatabase;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ranasgalla.niccolo
 */
public class GiteFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GiteFrame.class.getName());

     private Connection conn;
    /**
     * Creates new form GiteFrame
     */
    public GiteFrame(Connection conn) {
        this.conn = conn;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtDestinazione = new javax.swing.JTextField();
        txtDurata = new javax.swing.JTextField();
        txtPrezzo = new javax.swing.JTextField();
        btnCarica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSuccessivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("GITE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 470, 70));

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDestinazione.setBackground(new java.awt.Color(0, 0, 102));
        txtDestinazione.setForeground(new java.awt.Color(255, 255, 255));
        txtDestinazione.addActionListener(this::txtDestinazioneActionPerformed);
        jPanel1.add(txtDestinazione, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 90, -1));

        txtDurata.setBackground(new java.awt.Color(0, 0, 102));
        txtDurata.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtDurata, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 90, -1));

        txtPrezzo.setBackground(new java.awt.Color(0, 0, 102));
        txtPrezzo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtPrezzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 90, -1));

        btnCarica.setBackground(new java.awt.Color(0, 0, 102));
        btnCarica.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnCarica.setForeground(new java.awt.Color(255, 255, 255));
        btnCarica.setText("Carica");
        btnCarica.addActionListener(this::btnCaricaActionPerformed);
        jPanel1.add(btnCarica, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 230, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Destinazione");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 90, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Durata");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 60, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prezzo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 60, -1));

        btnSuccessivo.setBackground(new java.awt.Color(0, 0, 102));
        btnSuccessivo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnSuccessivo.setForeground(new java.awt.Color(255, 255, 255));
        btnSuccessivo.setText("Prossimo");
        btnSuccessivo.addActionListener(this::btnSuccessivoActionPerformed);
        jPanel1.add(btnSuccessivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 470, 50));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuccessivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuccessivoActionPerformed

        AlunniFrame g = new AlunniFrame(conn);
        g.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSuccessivoActionPerformed

    private void btnCaricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaricaActionPerformed
        try {
            String destinazione = txtDestinazione.getText();
            if(destinazione.isEmpty()){
                JOptionPane.showMessageDialog(null, "Il campo Destinazione non può essere vuoto!", "Errore", JOptionPane.ERROR_MESSAGE);
            return;
            }
            if(destinazione.matches("[a-zA-Z ]+")){
                JOptionPane.showMessageDialog(null, "Il campo Destinazione deve avere solo lettere!", "Errore", JOptionPane.ERROR_MESSAGE);
            return;
            }
            String durataTesto = txtDurata.getText().trim();
            if(durataTesto.isEmpty()){
                JOptionPane.showMessageDialog(null, "Il campo Durata non può essere vuoto!", "Errore", JOptionPane.ERROR_MESSAGE);
            return;
            }
            if (!durataTesto.matches("\\d+")) {
                JOptionPane.showMessageDialog(null, "Durata deve contenere solo numeri interi!", "Errore", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int durata = Integer.parseInt(durataTesto);
            String prezzoTesto = txtPrezzo.getText().trim();

            if (prezzoTesto.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Il campo Prezzo non può essere vuoto!", "Errore", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!prezzoTesto.matches("\\d+")) {
                JOptionPane.showMessageDialog(null, "Prezzo deve contenere solo numeri!", "Errore", JOptionPane.ERROR_MESSAGE);
                return;
            }

int prezzo = Integer.parseInt(prezzoTesto);

            PreparedStatement check = conn.prepareStatement(
                    "SELECT COUNT(*) FROM Gite WHERE GIT_Destinazione = ? AND GIT_Durata = ? AND GIT_Prezzo = ?"
            );
            check.setString(1, destinazione);
            check.setInt(2, durata);
            check.setInt(3, prezzo);
            ResultSet rs = check.executeQuery();
            rs.next();
            int count = rs.getInt(1);
            rs.close();
            check.close();

            if (count > 0) {
                JOptionPane.showMessageDialog(null,
                        "Esiste già una gita a " + destinazione + " con la durata di " + durata + " e il prezzo di " + prezzo,
                        "Duplicata",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            // Se il controllo passa inserisce
            PreparedStatement pstmt = conn.prepareStatement(
                    "INSERT INTO Gite (GIT_Destinazione, GIT_Durata, GIT_Prezzo) VALUES (?, ?, ?)"
            );
            pstmt.setString(1, destinazione);
            pstmt.setInt(2, durata);
            pstmt.setInt(3, prezzo);
            pstmt.execute();
            pstmt.close();

            JOptionPane.showMessageDialog(null, "Gita inserita con successo!");

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCaricaActionPerformed

    private void txtDestinazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinazioneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinazioneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarica;
    private javax.swing.JButton btnSuccessivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDestinazione;
    private javax.swing.JTextField txtDurata;
    private javax.swing.JTextField txtPrezzo;
    // End of variables declaration//GEN-END:variables
}
