/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dangeranabinigitedatabase;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author dangelo.gregorio
 */
public class PartecipazioniFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PartecipazioniFrame.class.getName());

    private Connection conn;
    /**
     * Creates new form Partecipazioni
     */
    public PartecipazioniFrame(Connection conn) {
        initComponents();
        this.conn = conn;
        caricaAlunni();
        caricaGite();
    }

     private void caricaAlunni() {
        try {
            cmbAlunni.removeAllItems();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT ALU_Matricola, ALU_Nome, ALU_Cognome FROM Alunni");
            while (rs.next()) {
                // es. "1 - Mario Rossi"
                String voce = rs.getInt("ALU_Matricola") + " - " + rs.getString("ALU_Nome") + " " + rs.getString("ALU_Cognome");
                cmbAlunni.addItem(voce);
            }
            rs.close();
            stmt.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
     
     private void caricaGite() {
        try {
            cmbGite.removeAllItems();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT GIT_ID, GIT_Destinazione FROM Gite");
            while (rs.next()) {
                // es. "1 - Roma"
                String voce = rs.getInt("GIT_ID") + " - " + rs.getString("GIT_Destinazione");
                cmbGite.addItem(voce);
            }
            rs.close();
            stmt.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbAlunni = new javax.swing.JComboBox<>();
        cmbGite = new javax.swing.JComboBox<>();
        btnCarica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Studente");

        jLabel2.setText("Gite");

        cmbAlunni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbGite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCarica.setText("Carica");
        btnCarica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaricaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(cmbAlunni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnCarica)
                .addGap(18, 18, 18)
                .addComponent(cmbGite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAlunni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbGite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarica))
                .addContainerGap(218, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaricaActionPerformed
        try {
            // "1 - Mario Rossi" prende "1"
            String voceAlunno = (String) cmbAlunni.getSelectedItem();
            int aluId = Integer.parseInt(voceAlunno.split(" - ")[0]);

            // "1 - Roma" prende "1"
            String voceGita = (String) cmbGite.getSelectedItem();
            int gitId = Integer.parseInt(voceGita.split(" - ")[0]);

            PreparedStatement pstmt = conn.prepareStatement(
                "INSERT INTO Partecipazione (PAR_ALU_ID, PAR_GIT_ID) VALUES (?, ?)"
            );

            pstmt.setInt(1, aluId);
            pstmt.setInt(2, gitId);
            pstmt.execute();
            pstmt.close();

            JOptionPane.showMessageDialog(null, "Partecipazione inserita con successo!");

        } catch (SQLException e) {
            e.printStackTrace();
        }
    
    }//GEN-LAST:event_btnCaricaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarica;
    private javax.swing.JComboBox<String> cmbAlunni;
    private javax.swing.JComboBox<String> cmbGite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
